### PR TITLE
Ian testing

### PR DESCRIPTION
**Pull request by s-iloo**
Added Cypress tests that run through each page testing basic functionality. Home -> Login -> Transaction -> Signup -> Account

### CODE REVIEW

**Comment by 2guud4u** [comment]
looks great

**Comment by jackherberger** [comment]
Looks good to me - I like Cypress as a front end testing platform.

**Comment by jinpettit** [comment]
Ran the test cases on my end and they all passed. Good work

**Review by QuietDruid — APPROVED** [review]
Great framework + tweaks to program to deal with testing! Got my sign off

**Review by jinpettit — APPROVED** [review]

**Pull request merged**
