### PR TITLE
Connect login

### PR DESCRIPTION
**Pull request by QuietDruid**
Going back to main, tweaked functionailty a bit on transaction side - need a second pair of eyes but should be ok. Graphs are borked but not within scope rn.

### CODE REVIEW

**Review by 2guud4u — APPROVED** [review]
looks good. However, I am not sure what dot env is.

**Comment by s-iloo** [comment]
Looks like everything is working on my end. Great work!

**Comment by jinpettit** [comment]
Everything works on my end. Just need to resolve merge conflicts

**Comment by jackherberger** [comment]
Looks all good over here too.

**Review by jinpettit — APPROVED** [review]

**Comment by jinpettit** [comment]
Merged in another version

**Pull request closed without merging**
